In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [52]:
class AutoEncoder:
    
    def __init__(self, hiddenlayer_units:int , learning_rate : int, dimension:tuple , epochs:int):
        
        self.output_dimension = dimension[-1] 
        self.input_dimension = dimension[-1]
        self.output_bias = np.random.randn(dimension[-1])
        self.hidden_bias = np.random.randn(hiddenlayer_units)
        self.hidden_wights = np.random.randn(self.input_dimension , hiddenlayer_units)
        self.output_weights = np.random.randn(hiddenlayer_units , self.input_dimension)
        self.epochs = epochs
        self.learning_rate = learning_rate
    
    def train_autoencoder(self , train):
        
        for i in range(self.epochs):
            print(f"Epoch : {i}")
            
            hidden_output = train.values@self.hidden_wights + self.hidden_bias
            
            output_layer_output = hidden_output@self.output_weights + self.output_bias 
            
            loss = (output_layer_output - train.values)
            
            self.output_bias = self.output_bias - (self.learning_rate*np.sum(loss , axis=0))/(train.shape[0])
            
            updated_needed = hidden_output.T @ loss 
            
            self.output_weights = self.output_weights - (self.learning_rate*updated_needed)/(train.shape[0])
            
            self.hidden_wights  = self.hidden_wights - (self.learning_rate*(loss.T@train.values)@(self.output_weights.T))/(train.shape[0])  
            
            self.hidden_bias -= (self.learning_rate*(np.sum(loss , axis=0).T@(self.output_weights.T))) /(train.shape[0])
            
            print(self.hidden_wights)
    
    def transform_data(self , data):
        
        return data.values@self.hidden_wights

In [28]:
data = pd.DataFrame(

    {
        'x' : np.random.randn(1000),
        'y' : np.random.randn(1000),
        'z' : np.random.randn(1000)
    }
    
)

In [53]:
auto_encoding = AutoEncoder(2,0.01 , data.shape , 100)

In [54]:
auto_encoding.train_autoencoder(data)

Epoch : 0
[[ 0.52289234  0.00239563]
 [-0.13626144  0.08334331]
 [-0.02054042 -0.33468341]]
Epoch : 1
[[ 0.51796139  0.00077492]
 [-0.1448447   0.09068896]
 [-0.01615466 -0.32364028]]
Epoch : 2
[[ 5.14230275e-01  4.64823092e-04]
 [-1.52787256e-01  9.84707341e-02]
 [-1.30217400e-02 -3.14074727e-01]]
Epoch : 3
[[ 0.51142582  0.00113302]
 [-0.1602065   0.10655453]
 [-0.01082654 -0.30560568]]
Epoch : 4
[[ 0.50935344  0.00254431]
 [-0.16718656  0.11484678]
 [-0.00934768 -0.29796748]]
Epoch : 5
[[ 0.50787012  0.00452691]
 [-0.17378973  0.12328028]
 [-0.00842489 -0.29096931]]
Epoch : 6
[[ 0.50686805  0.00695208]
 [-0.18006339  0.13180563]
 [-0.00793927 -0.28447077]]
Epoch : 7
[[ 0.50626415  0.00972114]
 [-0.18604441  0.14038577]
 [-0.0078007  -0.27836637]]
Epoch : 8
[[ 0.50599324  0.01275702]
 [-0.19176207  0.14899248]
 [-0.00793973 -0.27257551]]
Epoch : 9
[[ 0.50600337  0.0159985 ]
 [-0.19723998  0.157604  ]
 [-0.00830199 -0.26703566]]
Epoch : 10
[[ 0.50625259  0.01939625]
 [-0.20249749  0.1

In [43]:
test_data = pd.DataFrame(
    
    {
        'x' : np.random.randn(100),
        'y' : np.random.randn(100),
        'z' : np.random.randn(100)
    }

)

In [44]:
test_data

x         y         z
0  -1.527542  0.399115 -0.053944
1  -1.481385 -1.002075 -0.503720
2   0.464720  0.916486 -0.921343
3  -0.100736 -0.973460 -0.858357
4  -0.294076 -0.268134  0.818228
..       ...       ...       ...
95  0.080287 -0.187072 -0.292096
96  0.434601  1.368543 -0.728149
97 -0.169606 -0.251250  0.653405
98 -0.658795  1.359024  1.251024
99 -1.068175  1.421531 -0.489127

[100 rows x 3 columns]

In [55]:
auto_encoding.transform_data(test_data)

array([[-1.24626495,  0.35244575],
       [-0.95305438, -0.79075927],
       [ 0.22614126,  0.51515287],
       [ 0.11750449, -0.88490115],
       [-0.20445011, -0.04826247],
       [ 0.52002185,  0.30347283],
       [ 0.83046342,  0.27973193],
       [-0.18970676,  1.58390817],
       [ 0.13907852, -0.32965527],
       [-0.38000496, -0.22830954],
       [-1.09080895,  0.3719182 ],
       [-0.4413456 ,  0.85102495],
       [ 0.44027988, -0.60463288],
       [ 0.69952257,  0.11484508],
       [ 1.63944828, -0.12353734],
       [ 1.33668606,  0.63461074],
       [ 0.11447138, -0.68138382],
       [-0.41783296, -0.20958328],
       [ 0.62841824, -1.83097535],
       [ 0.29078091,  0.106675  ],
       [-0.94643671, -0.23095199],
       [-0.05725838, -1.2820683 ],
       [-0.35816186,  1.38920766],
       [ 0.52773334,  1.09587881],
       [ 0.02684346,  0.47109805],
       [ 1.08112209, -0.55878923],
       [ 1.06855227, -0.70320184],
       [-0.83580478,  2.05944902],
       [ 0.2412281 ,